pipeline {
    agent any

    environment {
        IMAGE_NAME = 'dodaharsha/cd-app'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/HarshaDoda/cd-project.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('app') {
                    bat 'npm test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    bat "docker build -t %IMAGE_NAME% ."
                }
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    bat '''
                    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    docker push %IMAGE_NAME%
                    '''
                }
            }
        }

        stage('Deploy via Helm') {
            steps {
                bat 'helm upgrade --install myapp ./helm/myapp --set image.repository=%IMAGE_NAME%'
            }
        }
    }

    // post {
    //     success {
    //         slackSend(channel: '#devops-alerts', message: "✅ Success: ${env.JOB_NAME} #${env.BUILD_NUMBER}")
    //     }
    //     failure {
    //         slackSend(channel: '#devops-alerts', message: "❌ Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}")
    //     }
    // }
}
